{% set name = "awscli-cwlogs" %}
{% set version = "1.4.6" %}
{% set sha256 = "44d2fe77d109b7b630fb8f6c06760ff6c5ec9861be16413fd5b977f5a4971f83" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - awscli >=1.11.41
    - six >=1.1.0
    - python-dateutil >=2.1

test:
  imports:
    - cwlogs

about:
  home: http://aws.amazon.com/cli/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: AWSCLI CloudWatch Logs plugin
  description: |
    This awscli plugin provides the pull, push and filter commands to
    access AWS CloudWatch Logs service.
  doc_url: http://aws.amazon.com/cli/

extra:
  recipe-maintainers:
    - CurtLH
