travis:
  secure:
    BINSTAR_TOKEN: zU+uHcjKfxE/jH6tNILng+GCqNcjV1lYYqYBlrVlCS343iAp7EDw3GpOCCyBYfgAgNa537VXOjLUwNbssJod7dSdBn2sUnd1FglW5AFyYuO18JdCt+kV/pJyGBgpqyPolikuxZl7VrcAjVqUVH++68ZnygMlZE4gVOqbrGPll1mfK3H7ASvbiK70BeW70Jw2qpJsMK+5OPG9GhVmpcoXejOAZrCm2fff3eAh/STLtUl9GoBhJK/+s1+Gwl8oRj8hP0mDJr7lvDIpe0cs7ivkTaTzec0uDxd2ZuYpHOfSC6LqCy5EnIfjuC30bghFGRQ96Vk8XEE3LethdlQD1OhAgvzm8s52Ujc2lPQHmSXWo+QGrqBGciNkfQbQvg9YnIC050gSlTzvovg5EjGzOAcqMsPrm5SDWLtGGxRDLWMKQIhQCYr2rUnpgGrhL4TcJ9Hyvx9I0yEchw+5j1j0PzlkE2bNh2W672lEFbWUaL4bCU2MHomi/SeOmREMD06zSo204hOj+rnLg1rbi5Q7dKMJojWbq2szgvzKNwFGEHWfIwYFxhZ420Tr+doxkHnvV0SpMpm0IN+GmaX4JdxhaJhoBId3kAFAQvPFHAF/0OIDhSZQhnQv+Ov5USqvCRXscTbFdle7ZLbfUEX5f0eTC/5+h9gIVD6cLY6qd2d2tqRL0lQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
