travis:
  secure:
    BINSTAR_TOKEN: uaDYuHz/Hp3yd/FHS/77EDfNGNxXkJAS1QrPBF69KQ2lEobL5j3uB/lIxQZNzxlJTHHXQqDs6bOhT9iXeqylXjk6VGfSU5yerW8V6NjRgBLym7ZikZi9bMzw6bTt2DlFvTzo+3W0I+hbWgTRsTH+asIAd50YVRhNVMiU3iwZGvjOHnjuGX1hsx1MnsnEDN5jSQmZU9ZsF5AKc3zJ/1V96gGwaIQHsXVLIYowzdx2henYj/QmX9zqTuypqQZgWI/9w4HLgcMkv5CbgsCIT720Nud56P6E3OUeZSIRlyx/MjUw2I/Pad1He3QEv/hC2TcpqdPLZMOFA1U7NESopJlvkUrmwmBINZivsR6QQ/c/FAQqRiy4CvnDkyfS2rg83SZ8kxRnDHI/9KhSApAlF1uR78nJWsjOg2Lr6AvqXksH+QkeRGyOInT/uxN4ULG+Sm5FJmId5hPIt64eX3qpEirLMC3d9TmllA+KXw8OK2BSLC7Jy2W5x9fk6PK/rNsYmDnPoQHj2yEw6BJ+HJpPAeQDa5iy2LGtMJ3QvQ0ElR/5h7H6ptu6ZWwtuH7UR8B7Qp5x5VeZkRVar/fqe3V+t+/4CQ/7jl1ntxsgeTn/Deue3sol6xZZUCkGpB0jV3jFbBEyKSaJ2fED5kAsxop2CFq2zk2LUK8l7b3trtNg04H/kqk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
